name: 'Go Build and Test'
description: 'Runs go build and go test using a matrix for the OS.'
permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-15, macOS-26, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
      - run: go mod tidy
      - run: echo "Running build on ${{ matrix.os }}"
      - run: go build -v ./...
      - run: go test -race ./...
