name: 'Run golangci-lint'
description: 'Runs golangci-lint on the repository.'

on:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
